### ISSUE TITLE
Matrix Factorization 코드 관련 업데이트 사항 반영 요청.

### ISSUE THREAD

**Issue by m4a1carbin4** [lsjsj92/recommender_system_with_Python#1]
pandas 기준 사용자 df_user_movie_ratings를 일반 numpy 매트릭스로 변환하기 위해 사용하는 as_matrix() 함수가 Deprecated since version 0.23.0: 상태 임으로 이에 대하여 대체 함수인 to_numpy()로 변경 해야할 필요성이 있으므로 이에대해 이슈탭 남기고 사라집니다.

**Comment by lsjsj92** [comment]
안녕하세요~ 네네 감사합니다! 시간 되는대로 반영해서 수정해보겠습니다 :)
